administrator:
    resource: routing/administrator.yml
    host: "%administrator_host%"

doctor:
    resource: routing/doctor.yml
    host: "%doctor_host%"

patient:
    resource: routing/patient.yml
    host: "%patient_host%"


#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
