# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_DOCTOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        #fos_userbundle:
            #id: fos_user.user_provider.username
        doctor:
            id: doctor.user_provider.username_email
        administrator:
            id: administrator.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/((_(profiler|wdt)|css|images|js)/)|(browserconfig.xml$|manifest.json$)
            security: false

        doctor:
            pattern: ^/
            host: "%doctor_host_pattern%"
            form_login:
                provider: doctor
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

        administrator:
            pattern: ^/
            host: "%administrator_host_pattern%"
            form_login:
                provider: administrator
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: "%doctor_host_pattern%", roles: [ROLE_DOCTOR] }
        - { host: "%administrator_host_pattern%", roles: [ROLE_ADMIN] }

